### PR TITLE
fixes #2

### LINKED ISSUE #2: Take in account for panopto delay
Timestamp could be wrong for activities.

### PR DESCRIPTION
**Pull request by baggiodev**

### CODE REVIEW

File: client/src/App.js [hunk 1]
```diff
@@ -21,23 +21,16 @@ class App extends Component {
...
-	return minutes + ":" + seconds;
-  }
+ secondsToHms(d) {
+    d = Number(d);
+
+    var h = Math.floor(d / 3600);
+    var m = Math.floor(d % 3600 / 60);
+    var s = Math.floor(d % 3600 % 60);
+
+    return ("0" + h).slice(-2) + ":" + ("0" + m).slice(-2) + ":" + ("0" + s).slice(-2);
```
Comment (Thunderducky) [inline client/src/App.js:53]: You should add a comment explaining this line, since it's not immediately obvious what you are doing

File: server.js [hunk 2]
```diff
@@ -109,7 +109,10 @@ app.get("/api/activities", (req,res)=>{
     	res.json(data);
     }
   ).catch(
-    err => res.status(500).send(err)
+    (err) => {
+		console.log(err);
```
Comment (Thunderducky) [inline server.js:113]: Should probably remove this console.log :)

**Review by Thunderducky — CHANGES_REQUESTED** [review]
Just a few nitpicky issues, otherwise looks good, resubmit and I'll approve it

**Review by Thunderducky — APPROVED** [review]
Looks fine to me
